id: autohotkey
name: Autohotkey
version: 1.1.33.01
home: https://www.autohotkey.com/
repo: https://github.com/Lexikos/AutoHotkey_L/
license: GNU General Public License v2.0
installMethod: Custom
args:
  silent: /S
installers:
- location: https://www.autohotkey.com/download/ahk-install.exe
  sha256: 743955400da24deccfd38041be68a83403f4641d927864fad49e4d6154871598
